### ISSUE TITLE
Consider bundling the schema function in an extension

### ISSUE THREAD

**Issue by strk** [linz/linz_bde_uploader#55]
This ticket is for discussion: any reason not to wrap the sql/* scripts into a `bde_uploader` extension ?

\cc @palmerj @imincik

**Comment by palmerj** [comment]
Yes it could be, but it needs wider consideration.

One of the specific issues that needs to be considered is how we might package up the software in the 2nd iteration of the LDS migration project. At the moment we have the following packages that make up the BDE Processor:

- linz_bde_uploader (Perl and SQL)
- linz_utils_perl (Perl)
- linz_bde_perl (Perl)
- linz_bde_copy (c++)
- linz-bde-schema (SQL)
- linz-lds-bde-schema (SQL)
- linz-postgresql-functions (SQL)
- postgresql-tableversion (extension)
- postgresql-dbpatch (SQL extension)

We split up the linz-bde-schema and linz-lds-bde-schema and linz_bde_uploader (SQL code) because there was a use case (linz-gdb-postgres and AIMS) for only installing the BDE processor for internal use without all the lds-* packages. If we move to a new architecture as outlined by @imincik in the LDS migration project then this potentially changes.

**Comment by imincik** [comment]
I also like extension idea, but I would wait until some redesign is done. 

BTW, @palmerj , I updated BDE Processor deployment docs with your nice list of components (https://github.com/linz/bde-processor-deployment/blob/master/README.md)

**Comment by palmerj** [comment]
Thanks @imincik

**Comment by strk** [comment]
Let's not do this as we're actually going the other way to be more flexible and be able to use not-fully-controlled database servers, see #127
